<?php
/** @var Magento\Framework\View\Element\Template $block */

$blogViewModel = $block->getData('viewModel');
?>

<div class="blog-container" data-bind="scope: 'blog'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "blog": {
                        "component": "UnityGroup_Blog/js/blog",
                        "posts": <?= $blogViewModel->getPosts(); ?>
                    }
                }
            }
        }
    }
</script>
